# Generated by Django 4.1.2 on 2022-11-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="Age",
            field=models.CharField(default=0, max_length=2),
        ),
    ]
