# Generated by Django 4.1.2 on 2022-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_candidate_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="phone",
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name="candidate", name="Age", field=models.CharField(max_length=2),
        ),
    ]
