# Generated by Django 4.1.2 on 2022-11-18 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_candidate_phone_alter_candidate_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job",
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidate", name="phone", field=models.CharField(max_length=15),
        ),
    ]
