# Generated by Django 4.1.2 on 2022-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_candidate_job_alter_candidate_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="Situation",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Disapproved", "Disapproved"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
